___

<a href='http://www.pieriandata.com'><img src='../Pierian_Data_Logo.png'/></a>
___
<center><em>Авторские права принадлежат Pierian Data</em></center>
<center><em>Для дополнительной информации посетите наш сайт <a href='http://www.pieriandata.com'>www.pieriandata.com</a></em></center>

# Упражнения по NumPy

Давайте проверим Ваши знания NumPy. Мы начнём с достаточно простых задач, и плавно перейдём к более сложным.

<div class="alert alert-danger" style="margin: 10px"><strong>ВАЖНОЕ ЗАМЕЧАНИЕ!</strong> Пожалуйста не запускайте ячейки, которые располагаются <br> непосредственно над ожидаемым результатом, иначе Вы удалите этот ожидаемый результат!</div>

#### 1. Импортируйте NumPy as np

In [52]:
import numpy as np

#### 2. Создайте массив из 10 нулей

In [53]:
# Напишите Ваше решение в этой ячейке
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [54]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


#### 3. Создайте массив из 10 единиц

In [55]:
# Напишите Ваше решение в этой ячейке
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [56]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


#### 4. Создайте массив из 10 пятёрок

In [57]:
# Напишите Ваше решение в этой ячейке
np.full(10,5.)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [58]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


#### 5. Создайте массив целых чисел от 10 до 50 включительно

In [59]:
# Напишите Ваше решение в этой ячейке
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [60]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


#### 6. Создайте массив всех чётных чисел от 10 до 50 включительно

In [61]:
# Напишите Ваше решение в этой ячейке
np.arange(10,51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [62]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


#### 7. Создайте матрицу 3x3 со значениями от 0 до 8 включительно

In [95]:
# Напишите Ваше решение в этой ячейке
np.array([[1,2,3], [4,5,6], [7,8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


#### 8. Создайте единичную матрицу размером 3x3

In [65]:
# Напишите Ваше решение в этой ячейке
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


#### 9. С помощью NumPy сгенерируйте случайное число в диапазоне от 0 до 1<br><br>&emsp;Замечание: Ваш результат может отличаться от того, что указано в качестве примера ниже.

In [111]:
# Напишите Ваше решение в этой ячейке
np.random.seed(1)

In [104]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


#### 10. С помощью NumPy сгенерируйте массив из 25 случайных чисел, выбранных из стандартного нормального распределения<br><br>&emsp;&ensp;Замечание: Ваш результат может отличаться от того, что указано в качестве примера ниже.

In [69]:
# Напишите Ваше решение в этой ячейке


In [70]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


#### 11. Создайте указанную ниже матрицу:

In [71]:
# Напишите Ваше решение в этой ячейке


In [72]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


#### 12. Создайте массив из 20 равноудалённых друг от друга точек между 0 и 1:

In [73]:
# Напишите Ваше решение в этой ячейке


In [74]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


## Индексация Numpy

Здесь Вы будете работать с некоторой матрицей - чтобы создать её, запустите следующую ячейку! После этого мы попросим Вас воспроизвести несколько результатов работы с этой матрицей:

In [75]:
# ЗАПУСТИТЕ ЭТУ ЯЧЕЙКУ - ЭТО СОЗДАНИЕ МАТРИЦЫ ДЛЯ СЛЕДУЮЩИХ ЗАДАНИЙ
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу (подсказка - используйте индексацию).

In [76]:
# Напишите Ваше решение в этой ячейке


In [77]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


#### 14. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу.

In [78]:
# Напишите Ваше решение в этой ячейке


In [79]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


#### 15. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу.

In [80]:
# Напишите Ваше решение в этой ячейке


In [81]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


#### 16. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу.

In [82]:
# Напишите Ваше решение в этой ячейке


In [83]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


#### 17. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу.

In [84]:
# Напишите Ваше решение в этой ячейке


In [85]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


## Операции в NumPy

#### 18. Найдите сумму всех чисел в матрице mat

In [86]:
# Напишите Ваше решение в этой ячейке


In [87]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


#### 19. Найдите среднеквадратичное отклонение значений в матрице mat

In [88]:
# Напишите Ваше решение в этой ячейке


In [89]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


#### 20. Найдите сумму каждой из колонок в матрице mat

In [90]:
# Напишите Ваше решение в этой ячейке


In [91]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


## Бонусный вопрос

Мы много работали со случайными данными в numpy, но есть ли способ каждый раз получать одни и те же "случайные" результаты? [Для подсказки нажмите здесь](https://www.google.com/search?q=numpy+random+seed&rlz=1C1CHBF_enUS747US747&oq=numpy+random+seed&aqs=chrome..69i57j69i60j0l4.2087j0j7&sourceid=chrome&ie=UTF-8)

In [92]:
# Напишите Ваше решение в этой ячейке


# Отличная работа!